package de.slisson.mps.editor.aec.demolang.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"de.slisson.mps.editor.aec.demolang.structure.ConceptAA", "de.slisson.mps.editor.aec.demolang.structure.ConceptBA", "de.slisson.mps.editor.aec.demolang.structure.ConceptBAA", "de.slisson.mps.editor.aec.demolang.structure.RootConcept"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 0:
        return new ConceptAA_BehaviorDescriptor();
      case 1:
        return new ConceptBA_BehaviorDescriptor();
      case 2:
        return new ConceptBAA_BehaviorDescriptor();
      case 3:
        return new RootConcept_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
