package de.slisson.mps.editor.aec.demolang.behavior;

/*Generated by MPS */


public class ConceptBAA_BehaviorDescriptor extends ConceptBA_BehaviorDescriptor {
  public ConceptBAA_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.slisson.mps.editor.aec.demolang.structure.ConceptBAA";
  }
}
