package de.slisson.mps.editor.aec.demolang.behavior;

/*Generated by MPS */


public class ConceptBA_BehaviorDescriptor extends ConceptB_BehaviorDescriptor {
  public ConceptBA_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.slisson.mps.editor.aec.demolang.structure.ConceptBA";
  }
}
