package de.slisson.mps.editor.aec.demolang.behavior;

/*Generated by MPS */


public class ConceptAA_BehaviorDescriptor extends ConceptA_BehaviorDescriptor {
  public ConceptAA_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.slisson.mps.editor.aec.demolang.structure.ConceptAA";
  }
}
