package de.slisson.mps.editor.aec.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.EditorCellModel_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class AbstractEditorComponent_BehaviorDescriptor extends EditorCellModel_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public AbstractEditorComponent_BehaviorDescriptor() {
  }

  public boolean virtual_isCellIdInitialized_1229948571177(SNode thisNode) {
    return AbstractEditorComponent_Behavior.virtual_isCellIdInitialized_1229948571177(thisNode);
  }

  public String virtual_getOpeningText_1220339714057(SNode thisNode) {
    return AbstractEditorComponent_Behavior.virtual_getOpeningText_1220339714057(thisNode);
  }

  public String virtual_getClosingText_1220339738643(SNode thisNode) {
    return AbstractEditorComponent_Behavior.virtual_getClosingText_1220339738643(thisNode);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "de.slisson.mps.editor.aec.structure.AbstractEditorComponent";
  }
}
