package de.slisson.mps.editor.aec.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class AbstractEditorComponent_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getOpeningText_1220339714057(SNode thisNode) {
    return "?";
  }

  public static String virtual_getClosingText_1220339738643(SNode thisNode) {
    return "?";
  }

  public static boolean virtual_isCellIdInitialized_1229948571177(SNode thisNode) {
    return true;
  }
}
