package de.slisson.mps.editor.aec.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.BaseEditorComponent_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class ConcreteEditorComponent_BehaviorDescriptor extends BaseEditorComponent_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public ConcreteEditorComponent_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "de.slisson.mps.editor.aec.structure.ConcreteEditorComponent";
  }
}
