package de.slisson.mps.editor.aec.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Aec_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("aa758a3a-f4ed-4695-b50c-b8b16712c2f3(de.slisson.mps.editor.aec)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
