package de.slisson.mps.editor.aec.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"de.slisson.mps.editor.aec.structure.AbstractEditorComponent", "de.slisson.mps.editor.aec.structure.ConcreteEditorComponent"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("de.slisson.mps.editor.aec.structure.AbstractEditorComponent", "jetbrains.mps.lang.editor.structure.EditorCellModel", false, new String[]{"jetbrains.mps.lang.editor.structure.EditorCellModel", "jetbrains.mps.lang.core.structure.INamedConcept"}, new String[]{}, new String[]{});
      case 1:
        return new CompiledConceptDescriptor("de.slisson.mps.editor.aec.structure.ConcreteEditorComponent", "jetbrains.mps.lang.editor.structure.BaseEditorComponent", false, new String[]{"jetbrains.mps.lang.editor.structure.BaseEditorComponent", "jetbrains.mps.lang.core.structure.INamedConcept"}, new String[]{}, new String[]{"abstractComponent"});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
