package de.slisson.mps.editor.aec.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.editor.behavior.EditorCellModel_Behavior;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.WeavingMappingRuleContext;
import jetbrains.mps.lang.editor.generator.baseLanguage.template.util.QueriesUtil;

public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_6179564151247372692(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8291359990510587306(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1210365098190(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return EditorCellModel_Behavior.call_getFactoryMethodName_1216812165609(_context.getNode(), _context);
  }

  public static SNode sourceNodeQuery_996730828436728652(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "cellModel", true);
  }

  public static SNode weaving_MappingRule_ContextNodeQuery_6179564151247372704(final IOperationContext opereationContext, final WeavingMappingRuleContext _context) {
    return QueriesUtil.getGeneratedClassByCellContainer(_context.getNode(), _context);
  }
}
