package de.slisson.mps.editor.aec.demolang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import de.slisson.mps.editor.aec.runtime.AecUtil;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class ConceptB_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_lmkldl_a(editorContext, node);
  }

  private EditorCell createAbstractEditorComponent_lmkldl_b0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = AecUtil.createConcreteEditorCell(node, "bProperties", editorContext);
    return editorCell;
  }

  private EditorCell createCollection_lmkldl_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_lmkldl_a");
    editorCell.addEditorCell(this.createConstant_lmkldl_a0(editorContext, node));
    editorCell.addEditorCell(this.createAbstractEditorComponent_lmkldl_b0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_lmkldl_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "editor for ConceptB");
    editorCell.setCellId("Constant_lmkldl_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
