package de.slisson.mps.editor.aec.demolang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import de.slisson.mps.editor.aec.runtime.AecUtil;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class ConceptA_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_77rcuh_a(editorContext, node);
  }

  private EditorCell createAbstractEditorComponent_77rcuh_b0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = AecUtil.createConcreteEditorCell(node, "properties", editorContext);
    return editorCell;
  }

  private EditorCell createAbstractEditorComponent_77rcuh_d0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = AecUtil.createConcreteEditorCell(node, "childs", editorContext);
    return editorCell;
  }

  private EditorCell createCollection_77rcuh_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_77rcuh_a");
    editorCell.addEditorCell(this.createConstant_77rcuh_a0(editorContext, node));
    editorCell.addEditorCell(this.createAbstractEditorComponent_77rcuh_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_77rcuh_c0(editorContext, node));
    editorCell.addEditorCell(this.createAbstractEditorComponent_77rcuh_d0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_77rcuh_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "properties:");
    editorCell.setCellId("Constant_77rcuh_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_77rcuh_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "childs:");
    editorCell.setCellId("Constant_77rcuh_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
