package de.slisson.mps.editor.aec.demolang.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Demolang_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("f8d44a97-3ef8-453c-8345-7b3b78e66c06(de.slisson.mps.editor.aec.demolang)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
