package de.slisson.mps.editor.aec.demolang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"de.slisson.mps.editor.aec.demolang.structure.ConceptA", "de.slisson.mps.editor.aec.demolang.structure.ConceptAA", "de.slisson.mps.editor.aec.demolang.structure.ConceptB", "de.slisson.mps.editor.aec.demolang.structure.ConceptBA", "de.slisson.mps.editor.aec.demolang.structure.ConceptBAA", "de.slisson.mps.editor.aec.demolang.structure.RootConcept"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("de.slisson.mps.editor.aec.demolang.structure.ConceptA", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{"propA1"}, new String[]{});
      case 1:
        return new CompiledConceptDescriptor("de.slisson.mps.editor.aec.demolang.structure.ConceptAA", "de.slisson.mps.editor.aec.demolang.structure.ConceptA", false, new String[]{"de.slisson.mps.editor.aec.demolang.structure.ConceptA"}, new String[]{"propertyAA1", "propertyAA2"}, new String[]{});
      case 2:
        return new CompiledConceptDescriptor("de.slisson.mps.editor.aec.demolang.structure.ConceptB", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{"propB1"}, new String[]{});
      case 3:
        return new CompiledConceptDescriptor("de.slisson.mps.editor.aec.demolang.structure.ConceptBA", "de.slisson.mps.editor.aec.demolang.structure.ConceptB", false, new String[]{"de.slisson.mps.editor.aec.demolang.structure.ConceptB"}, new String[]{"propBA1"}, new String[]{});
      case 4:
        return new CompiledConceptDescriptor("de.slisson.mps.editor.aec.demolang.structure.ConceptBAA", "de.slisson.mps.editor.aec.demolang.structure.ConceptBA", false, new String[]{"de.slisson.mps.editor.aec.demolang.structure.ConceptBA"}, new String[]{"propBAA1"}, new String[]{});
      case 5:
        return new CompiledConceptDescriptor("de.slisson.mps.editor.aec.demolang.structure.RootConcept", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{}, new String[]{});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
